// Package genvanillacatalogue writes block/vanilla_catalogue_table.go: for
// every file of the embedded vanilla block catalogue, the block it declares,
// keyed by the exact text it was read from. See block/vanilla_catalogue.go for
// why the engine wants that instead of parsing the files.
package genvanillacatalogue

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"sort"

	"github.com/stirante/featurelab/block"
	"github.com/stirante/featurelab/jsonc"
)

// Render returns the source of block/vanilla_catalogue_table.go for files,
// which must be block.DefaultBlocks() -- the table is looked up by binary
// search, so its rows must be in that function's id order.
//
// It fails, rather than writing a row, for any file whose minecraft:block
// holds more than a description with an identifier and an empty components
// object. A row says "this file declares this block and nothing else"; a file
// with a tag, a trait or a permutation is not that, and a row for it would
// make the engine forget whatever the file said. Supporting such a file means
// widening the row and the code that applies it, deliberately.
func Render(files []block.SourceFile) ([]byte, error) {
	if !sort.SliceIsSorted(files, func(i, j int) bool { return files[i].ID < files[j].ID }) {
		return nil, fmt.Errorf("files must be sorted by id, as block.DefaultBlocks returns them")
	}
	var buf bytes.Buffer
	fmt.Fprintf(&buf, `// Code generated by cmd/genvanillacatalogue; DO NOT EDIT.

package block

// vanillaCatalogue is the block each of the %d vanilla catalogue files
// declares, keyed by the file's id, length and checksum. Sorted by id. See
// vanilla_catalogue.go.
var vanillaCatalogue = [...]vanillaCatalogueRow{
`, len(files))
	for _, f := range files {
		identifier, err := bareIdentifier(f)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", f.ID, err)
		}
		fmt.Fprintf(&buf, "\t{%q, %d, %#016x, %q},\n", f.ID, len(f.Text), block.CatalogueChecksum(f.Text), identifier)
	}
	buf.WriteString("}\n")
	return format.Source(buf.Bytes())
}

// bareIdentifier returns the identifier f declares, or an error if f declares
// anything else that block.LoadBlockTags would read. It decodes the file the
// way LoadBlockTags does (comments stripped, then encoding/json), so "what this
// check saw" and "what the engine would have seen" are the same document.
func bareIdentifier(f block.SourceFile) (string, error) {
	if jsonc.HasUTF8BOM([]byte(f.Text)) {
		return "", fmt.Errorf("starts with a byte-order mark, which the engine warns about")
	}
	var root map[string]any
	if err := json.Unmarshal(jsonc.StripComments([]byte(f.Text)), &root); err != nil {
		return "", fmt.Errorf("does not parse: %w", err)
	}
	body, ok := root["minecraft:block"].(map[string]any)
	if !ok {
		return "", fmt.Errorf("has no minecraft:block object")
	}
	if err := onlyKeys(body, "minecraft:block", "description", "components"); err != nil {
		return "", err
	}
	desc, ok := body["description"].(map[string]any)
	if !ok {
		return "", fmt.Errorf("minecraft:block.description is not an object")
	}
	if err := onlyKeys(desc, "minecraft:block.description", "identifier"); err != nil {
		return "", err
	}
	identifier, _ := desc["identifier"].(string)
	if identifier == "" {
		return "", fmt.Errorf("minecraft:block.description.identifier is missing")
	}
	components, ok := body["components"].(map[string]any)
	if !ok || len(components) != 0 {
		return "", fmt.Errorf("minecraft:block.components is not an empty object")
	}
	return identifier, nil
}

func onlyKeys(m map[string]any, where string, allowed ...string) error {
	for k := range m {
		found := false
		for _, a := range allowed {
			found = found || k == a
		}
		if !found {
			return fmt.Errorf("%s declares %q, which a catalogue row cannot carry", where, k)
		}
	}
	for _, a := range allowed {
		if _, ok := m[a]; !ok {
			return fmt.Errorf("%s has no %q", where, a)
		}
	}
	return nil
}
