<script setup lang="ts">
// The bench's coverage of this page's type, from generated/coverage.json -- which is
// `featurelab types --json`, regenerated by the build. The wiki's coverage page copies the
// same facts into prose by hand; this reads them, so the badge on a type's page cannot say
// `implemented` after features/coverage.go has moved it to `partial`.
//
// Reads `typeId` from the page's front matter. A page without one renders nothing.
import { useData } from 'vitepress'
import { computed } from 'vue'
import coverage from '../../../generated/coverage.json'

interface Row {
  typeId: string
  status: string
  note?: string
}

const { frontmatter } = useData()
const row = computed<Row | undefined>(() => {
  const id = frontmatter.value.typeId as string | undefined
  if (!id) return undefined
  return (coverage.types as Row[]).find((t) => t.typeId === id)
})
const label = computed(() => {
  switch (row.value?.status) {
    case 'implemented':
      return 'Bench: implemented'
    case 'partial':
      return 'Bench: partial'
    case 'missing':
      return 'Bench: not implemented'
    case 'out_of_scope':
      return 'Bench: out of scope'
    default:
      return ''
  }
})
const title = computed(() => {
  if (!row.value) return ''
  const s = row.value.status
  if (s === 'implemented') return 'featurelab implements this type in full: no part of its JSON surface refuses, and no disclosed behavioural gap is open. The page\'s examples were run on it.'
  if (s === 'partial') return 'featurelab implements this type with a stated gap. The page\'s "What the bench does differently" section says what it is.'
  return 'featurelab does not implement this type. Examples on this page were not run on the bench.'
})
</script>

<template>
  <span v-if="row" :class="['fl-badge', `fl-badge--cov-${row.status}`]" :title="title">{{ label }}</span>
</template>
