// groups.ts -- author-declared groups of features, read from and written to the pack files.
//
// A group is PRESENTATION THE AUTHOR DECLARED: several features and rules the author decided to
// look at as one thing, with a name, and either spread out inside a frame or folded into one
// card. That is the whole of it. A group has no meaning to the game and no meaning to the engine;
// it is what a person thinks a pack is made of, written down so the next person opening the pack
// sees the same shape.
//
// Three decisions follow from that, and each rules something out:
//
//   - MEMBERSHIP, NAME AND STATE LIVE IN THE PACK FILES, as a `@featurelab:group` directive in a
//     comment on each member's root. Not in the per-user layout sidecar: a group is a statement
//     about the pack, and a statement kept where only one person can see it is a note to self,
//     not a shape. So collapsing a group -- which is also a statement, "these read as one" --
//     rewrites its members' files, and is committed with the pack like everything else in it.
//   - A GROUP IS NEVER INFERRED. Nothing here looks at names, directories or delegations and
//     decides that some features belong together. The only groups are the ones written down.
//   - EDITING A MEMBER CHANGES NOTHING ABOUT THE GROUP. This is the difference from a compound
//     (compounds/collapse.ts), whose files are GENERATED from its parameters and which therefore
//     ejects to plain nodes the moment one of them is edited by hand. A group's members were never
//     generated by anything; the directive is a label, and a label survives any edit to the thing
//     it is on.
//
// # The directive
//
//   // @featurelab:group <id> <expanded|collapsed> <name words...>
//
// on the ROOT of each member's file (JSONPath `$`). The id is a slug ([a-z0-9_-]+) derived from
// the name when the group is made and kept stable across renames, so a rename rewrites the name
// words and nothing else -- and so two groups can share a display name without becoming one. The
// state and the name are repeated in every member because there is no other file to put them in:
// a pack has no manifest of groups, and inventing one would be a file the engine has to skip and
// an author has to keep in step with N others.
//
// Repetition means members CAN disagree, and `readGroups` says what happens then: the commonest
// value wins, the disagreement is reported on the group, and nothing is silently rewritten. Two
// files that disagree about a name is a state somebody produced by editing a comment in a text
// editor, which is legitimate, and the editor's job is to show it and offer the fix, not to pick
// a side and overwrite the other.
//
// # Flat
//
// A feature belongs to at most one group and a group holds no groups. One directive per file is
// what makes the first true (a file with two is reported and the first is used); the second is
// simply not expressible in the directive, and that is deliberate -- nested groups are a tree
// editor's worth of interaction over a canvas whose whole difficulty is already density.
//
// # What this module does not do
//
// It never touches a file and never draws. `plan*` return the batch of directive writes and
// removals that an operation means, in the shape the engine's `annotateBatch` takes, and the
// webview posts them; `collapseGroups` returns a view graph and the renderer draws it. Both
// halves are pure so both are testable without a browser or an engine.

/** The directive's name, without the `@featurelab:` prefix. */
export const GROUP_DIRECTIVE = 'group'

/** The id prefix of the synthetic node a collapsed group draws as. Chosen so it cannot collide
 * with a feature identifier, which always carries a namespace and a colon after it -- `group:` IS
 * a namespace-shaped prefix, and a pack could in principle own it, so the check is stricter than
 * the prefix: see isGroupNodeId. */
export const GROUP_NODE_PREFIX = 'group:'

/** What a group id may look like. Lower-case, so a slug derived from any name is one. */
const GROUP_ID_PATTERN = /^[a-z0-9_-]+$/

/** Whether two directive names are the same directive.
 *
 * FOLD-INSENSITIVE, because the engine's own suppression already is: `suppressedByIgnore` in
 * wire/graphcheck.go matches `@featurelab:ignore` with `strings.EqualFold`, so one half of this
 * tool honoured a capital and the other half dropped it. `@featurelab:Group pumpkins expanded
 * Pumpkins` drew no group, warned nowhere, and read in the file exactly like one that worked --
 * which is the same silence a misplaced directive produces, arrived at from the other side.
 *
 * Recognising it is not the same as approving of it: readGroups reports the spelling, because
 * only the exact lower-case name survives a round trip through the engine's own writer. */
function sameDirectiveName(a: string, b: string): boolean {
  return a.toLowerCase() === b.toLowerCase()
}

/** Whether an annotation is a `@featurelab:group` directive, at any path and in any case. */
function isGroupDirective(a: GroupAnnotationWire): boolean {
  return sameDirectiveName(a.name, GROUP_DIRECTIVE)
}

/** Every group directive a node's file carries -- ROOT OR NOT, and however it is spelled.
 *
 * The one list that answers "how many of these are in this file", which is what both the removal
 * plan and the warnings need and what neither of them had: both used to filter on `jsonPath ===
 * '$'` first, so a directive written one line low was invisible to the reader AND survived the
 * removal that was supposed to take the file out of every group it is in. */
function groupDirectivesOf(node: GroupNodeWire): readonly GroupAnnotationWire[] {
  return (node.annotations ?? []).filter(isGroupDirective)
}

// ---------------------------------------------------------------------------
// The wire, as this module needs it
// ---------------------------------------------------------------------------

/** One step of the engine's `annotateBatch`: the same three coordinates `annotate` takes, plus
 * `remove`, which takes the directive OUT instead of writing it. Spelled here, in the one module
 * that plans them, so the host relays them without re-shaping. */
export interface AnnotateOp {
  /** Pack-relative, as wire.GraphNode.File reports it. */
  readonly file: string
  /** What the directive is about, in jsonc.FormatPath's dialect; `$` for the file itself. */
  readonly path: string
  readonly name: string
  readonly args?: readonly string[]
  readonly remove?: boolean
}

/** The slice of wire.Annotation this module reads. */
export interface GroupAnnotationWire {
  readonly name: string
  readonly args?: readonly string[]
  readonly jsonPath: string
}

/** The slice of wire.GraphNode this module reads. */
export interface GroupNodeWire {
  readonly id: string
  readonly file?: string
  readonly unresolved?: boolean
  readonly external?: boolean
  readonly annotations?: readonly GroupAnnotationWire[]
}

export interface GroupEdgeWire {
  readonly from: string
  readonly to: string
  readonly kind: string
}

export interface GroupGraph {
  readonly nodes: readonly GroupNodeWire[]
  readonly edges: readonly GroupEdgeWire[]
  readonly roots: readonly string[]
}

/** What the renderer is handed on a collapsed group's synthetic node, so it can draw the card
 * from the node alone. Mirrored by render.ts's GraphNodeGroupWire. */
export interface GroupNodeSummary {
  readonly id: string
  readonly name: string
  readonly count: number
  /** The members the card stands for, in graph order -- every one of them, drawn or not.
   *
   * A CARD THAT SAYS "3 features" NAMES NONE OF THEM. A collapsed group used to be a name and a
   * number: the hover said the same thing in longer words, and the only way to learn what was
   * inside was to select the card and read the panel. That is a fold nobody can read ACROSS --
   * the whole reason to collapse a group is to go on seeing the pack's shape, and a box whose
   * contents are unknowable is a hole in it. The renderer shows the first few and says how many
   * are left; the full list is here so it can choose how many without asking anyone. */
  readonly memberIds: readonly string[]
}

// ---------------------------------------------------------------------------
// Reading
// ---------------------------------------------------------------------------

export interface FeatureGroup {
  readonly id: string
  readonly name: string
  readonly collapsed: boolean
  /** In graph order. Never empty: a group with no members is not a group, it is the absence of
   * one, and `readGroups` never returns it. */
  readonly memberIds: readonly string[]
  /** Disagreements between members, one line each, for the panel to show as notes. */
  readonly warnings: readonly string[]
}

export interface GroupsView {
  /** In order of first appearance in the graph. */
  readonly groups: readonly FeatureGroup[]
  readonly byId: ReadonlyMap<string, FeatureGroup>
  /** Node id -> the id of the group it belongs to. */
  readonly memberOf: ReadonlyMap<string, string>
  /** Node id -> what is wrong with THAT FILE's directives, one line each.
   *
   * The same sentences appear on the group they are about, and they have to appear here too,
   * because the group's panel is not where the author is standing when the file is the problem. A
   * node carrying two directives shows one group on its row and silently belongs to another the
   * moment the first is taken off -- and the only warning about it used to be on the panel of the
   * group that happened to win. See the `None` path in the webview's groupRow. */
  readonly nodeWarnings: ReadonlyMap<string, readonly string[]>
  /** Directives that could not be read as a group at all, one line each. */
  readonly warnings: readonly string[]
}

const EMPTY_VIEW: GroupsView = { groups: [], byId: new Map(), memberOf: new Map(), nodeWarnings: new Map(), warnings: [] }

interface ParsedDirective {
  readonly id: string
  readonly collapsed: boolean
  readonly name: string
}

/** Reads one directive's arguments, or says why they are not a group. */
function parseDirective(args: readonly string[] | undefined): { ok: true; value: ParsedDirective } | { ok: false; why: string } {
  const list = args ?? []
  const id = list[0]
  const state = list[1]
  if (id === undefined || state === undefined || list.length < 3) {
    return { ok: false, why: 'it needs an id, a state and a name' }
  }
  if (!GROUP_ID_PATTERN.test(id)) return { ok: false, why: `"${id}" is not a group id (letters, digits, - and _ only)` }
  if (state !== 'expanded' && state !== 'collapsed') return { ok: false, why: `"${state}" is neither expanded nor collapsed` }
  const name = normaliseGroupName(list.slice(2).join(' '))
  if (name === '') return { ok: false, why: 'the name is empty' }
  return { ok: true, value: { id, collapsed: state === 'collapsed', name } }
}

/** The commonest value in a list, ties to the first seen, and whether there was any disagreement. */
function majority<T>(values: readonly T[], describe: (v: T) => string): { value: T; note: string | null } {
  const counts = new Map<T, number>()
  for (const v of values) counts.set(v, (counts.get(v) ?? 0) + 1)
  let best: T = values[0] as T
  let bestCount = 0
  for (const [v, n] of counts) {
    if (n > bestCount) {
      best = v
      bestCount = n
    }
  }
  if (counts.size <= 1) return { value: best, note: null }
  const parts = [...counts.entries()].map(([v, n]) => `${describe(v)} ×${String(n)}`)
  return { value: best, note: parts.join(', ') }
}

/**
 * `graph` with `ops` folded into its nodes' annotations -- the graph as it will be once the host
 * has written them.
 *
 * WHAT THIS IS FOR. Every group operation is a ROUND TRIP: the panel posts a batch of directive
 * writes, the host writes each member's file, re-reads the pack and sends a graph back, and only
 * then does the panel know what the group is called or whether it is folded. Until that lands --
 * a couple of hundred milliseconds on an ordinary pack, which is well inside one person's second
 * click -- every group a plan is made against still carries its OLD name and its OLD state. And a
 * directive is rewritten WHOLE (`<id> <state> <name...>`), so the next operation does not add to
 * the one before it, it undoes it: rename a group and fold it a moment later, and the fold writes
 * the name back to what it was.
 *
 * So the operations already asked for are folded in before the next plan is made. This changes
 * nothing that is DRAWN -- the canvas still redraws only from a graph the host has re-read, as
 * everything else in this editor does -- and the panel drops these the moment an answer arrives.
 *
 * An op is matched to a node by FILE, because that is what an op addresses; several members of
 * one group are several ops. Writing replaces any directive of the same name at the same path,
 * exactly as the engine's annotate does, so folding the same op in twice says the same thing.
 */
export function withDirectives(graph: GroupGraph, ops: readonly AnnotateOp[]): GroupGraph {
  if (ops.length === 0) return graph
  const byFile = new Map<string, AnnotateOp[]>()
  for (const op of ops) {
    const list = byFile.get(op.file)
    if (list) list.push(op)
    else byFile.set(op.file, [op])
  }
  return {
    ...graph,
    nodes: graph.nodes.map((node) => {
      const forFile = node.file === undefined ? undefined : byFile.get(node.file)
      if (forFile === undefined) return node
      let annotations: GroupAnnotationWire[] = [...(node.annotations ?? [])]
      for (const op of forFile) {
        // The name comparison is fold-insensitive for the same reason readGroups's is: a file
        // carrying `@featurelab:Group` holds a directive this module counts, and a planned
        // removal that did not match it would leave the planned view showing a group the plan
        // has just taken the file out of. See isGroupDirective.
        annotations = annotations.filter((a) => !(sameDirectiveName(a.name, op.name) && a.jsonPath === op.path))
        if (op.remove !== true) annotations.push({ name: op.name, args: [...(op.args ?? [])], jsonPath: op.path })
      }
      return { ...node, annotations }
    }),
  }
}

/** Every group the graph's files declare.
 *
 * Read from the nodes as handed in, so a caller that has already hidden a compound's children
 * gets groups without those children -- a node that is not drawn cannot be a member of anything
 * drawn. Nodes with no file carry no annotations and so are never members. */
export function readGroups(graph: GroupGraph): GroupsView {
  const members = new Map<string, { node: GroupNodeWire; directive: ParsedDirective }[]>()
  const order: string[] = []
  const warnings: string[] = []
  const perGroupWarnings = new Map<string, string[]>()
  const nodeWarnings = new Map<string, readonly string[]>()

  for (const node of graph.nodes) {
    if (!node.file) continue
    // EVERY group directive in the file, wherever it is and however it is spelled -- then the
    // ones that can actually declare a group. The difference between the two lists is the whole
    // of what this block reports, and it used to be filtered away one line before the warning
    // path could see any of it.
    const all = groupDirectivesOf(node)
    const directives = all.filter((a) => a.jsonPath === '$')
    // A directive a line too low. The engine attaches a comment to the JSON value it precedes,
    // so `// @featurelab:group ...` written INSIDE the braces lands on `$.format_version` (or
    // whatever key follows it) rather than on the file. It is not a group and never was; it is
    // also not nothing, because the panel's own "None" has to take it off -- see removeOps -- and
    // because the next UI edit writes a second directive above the brace and leaves this one
    // underneath, permanently invisible.
    const misplaced = all.filter((a) => a.jsonPath !== '$')
    const nodeNotes: string[] = []
    for (const stray of misplaced) {
      nodeNotes.push(
        `${node.id} carries a @featurelab:group directive on ${stray.jsonPath} rather than on the file itself, ` +
          'so it declares no group. A group directive has to sit ABOVE the opening brace. ' +
          'Choosing a group for this feature from the panel rewrites all of them.',
      )
    }
    // A capital in the name. The engine reads `ignore` fold-insensitively (wire/graphcheck.go's
    // suppressedByIgnore), so a directive this half dropped on a spelling was one the other half
    // would have honoured, and the disagreement was silent at both ends.
    for (const odd of all.filter((a) => a.name !== GROUP_DIRECTIVE)) {
      nodeNotes.push(
        `${node.id} spells its directive @featurelab:${odd.name}; it is read as @featurelab:${GROUP_DIRECTIVE}. ` +
          `Write it lower case -- nothing else in this pack will match "${odd.name}".`,
      )
    }
    const first = directives[0]
    if (first === undefined) {
      // No group, but possibly something to say about why not.
      if (nodeNotes.length > 0) {
        warnings.push(...nodeNotes)
        nodeWarnings.set(node.id, nodeNotes)
      }
      continue
    }
    const parsed = parseDirective(first.args)
    if (!parsed.ok) {
      warnings.push(`${node.id}: its @featurelab:group directive was ignored -- ${parsed.why}.`, ...nodeNotes)
      if (nodeNotes.length > 0) nodeWarnings.set(node.id, nodeNotes)
      continue
    }
    const id = parsed.value.id
    if (nodeNotes.length > 0) {
      const list = perGroupWarnings.get(id) ?? []
      list.push(...nodeNotes)
      perGroupWarnings.set(id, list)
      nodeWarnings.set(node.id, nodeNotes)
    }
    if (!members.has(id)) {
      members.set(id, [])
      order.push(id)
    }
    members.get(id)!.push({ node, directive: parsed.value })
    if (directives.length > 1) {
      // Said on the group AND on the node. The node is where taking it out of a group goes
      // wrong -- one directive comes off and the next one takes over, which looks like the
      // feature moving itself into a group nobody chose.
      const line =
        `${node.id} carries ${String(directives.length)} group directives; the first one is used. ` +
        'Taking it out of a group removes all of them.'
      const list = perGroupWarnings.get(id) ?? []
      list.push(line)
      perGroupWarnings.set(id, list)
      // Appended rather than assigned: a file can be both misplaced-and-duplicated at once, and
      // the second finding used to replace the first wholesale.
      nodeWarnings.set(node.id, [...(nodeWarnings.get(node.id) ?? []), line])
    }
  }
  if (order.length === 0 && warnings.length === 0) return EMPTY_VIEW

  const groups: FeatureGroup[] = []
  const byId = new Map<string, FeatureGroup>()
  const memberOf = new Map<string, string>()
  for (const id of order) {
    const list = members.get(id)!
    const name = majority(list.map((m) => m.directive.name), (v) => `"${v}"`)
    const state = majority(list.map((m) => m.directive.collapsed), (v) => (v ? 'collapsed' : 'expanded'))
    const notes = [...(perGroupWarnings.get(id) ?? [])]
    if (name.note !== null) notes.push(`Members disagree about the name (${name.note}); showing the commoner one. Renaming fixes all of them.`)
    if (state.note !== null) notes.push(`Members disagree about being collapsed (${state.note}); showing the commoner state. Collapsing or expanding fixes all of them.`)
    const group: FeatureGroup = {
      id,
      name: name.value,
      collapsed: state.value,
      memberIds: list.map((m) => m.node.id),
      warnings: notes,
    }
    groups.push(group)
    byId.set(id, group)
    for (const m of list) memberOf.set(m.node.id, id)
  }
  return { groups, byId, memberOf, nodeWarnings, warnings }
}

/** What `readGroups` has to say about THIS node's own file, or an empty list. */
export function nodeGroupWarnings(view: GroupsView, nodeId: string): readonly string[] {
  return view.nodeWarnings.get(nodeId) ?? []
}

/** The group a node belongs to, or null. */
export function groupOf(view: GroupsView, nodeId: string): FeatureGroup | null {
  const id = view.memberOf.get(nodeId)
  return id === undefined ? null : (view.byId.get(id) ?? null)
}

// ---------------------------------------------------------------------------
// Names and ids
// ---------------------------------------------------------------------------

/** A name as it is stored: trimmed, inner whitespace collapsed to single spaces. The directive's
 * arguments are whitespace-split on the way back in, so this is the only spelling that survives
 * a round trip, and normalising up front is what makes "what I typed" equal "what I get back". */
export function normaliseGroupName(raw: string): string {
  return raw.replace(/\s+/g, ' ').trim()
}

/** Why a name cannot be written, or null when it can. */
export function validateGroupName(name: string): string | null {
  const clean = normaliseGroupName(name)
  if (clean === '') return 'A group needs a name.'
  // A directive may sit in a block comment, where this sequence would end the comment early and
  // turn the rest of the name into JSON the engine refuses.
  if (clean.includes('*/')) return 'A group name cannot contain "*/".'
  return null
}

/** The words a name is written as, one argument each. */
function nameWords(name: string): string[] {
  return normaliseGroupName(name).split(' ')
}

/** A fresh id for a group called `name`: the name as a slug, suffixed when the slug is taken.
 *
 * Stable across renames by construction -- it is only ever computed here, at creation -- so the
 * id is a handle and not a second copy of the name. */
export function slugForGroup(name: string, taken: Iterable<string>): string {
  const used = new Set(taken)
  const base =
    normaliseGroupName(name)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'group'
  if (!used.has(base)) return base
  for (let n = 2; n < 10_000; n++) {
    const candidate = `${base}-${String(n)}`
    if (!used.has(candidate)) return candidate
  }
  return `${base}-${String(Date.now())}`
}

export function groupNodeId(groupId: string): string {
  return `${GROUP_NODE_PREFIX}${groupId}`
}

/** The group id a synthetic node stands for, or null for an ordinary node. Stricter than the
 * prefix alone: the rest must be a valid group id, which no feature identifier's path is likely
 * to be, and which is what a caller then looks up anyway. */
export function groupIdOfNode(nodeId: string): string | null {
  if (!nodeId.startsWith(GROUP_NODE_PREFIX)) return null
  const rest = nodeId.slice(GROUP_NODE_PREFIX.length)
  return GROUP_ID_PATTERN.test(rest) ? rest : null
}

export function isGroupNodeId(nodeId: string): boolean {
  return groupIdOfNode(nodeId) !== null
}

// ---------------------------------------------------------------------------
// What may be grouped
// ---------------------------------------------------------------------------

/** Why a node cannot be a member, or null when it can.
 *
 * Only a node with a real file can carry the directive, so only a node with a real file can be a
 * member: not a dangling reference, not one of the game's own features, not the synthetic card
 * of another group. A hidden child of a collapsed compound is not in the graph this module is
 * handed, so it never reaches here -- and that is right: the compound stands for it. */
export function groupableReason(node: GroupNodeWire): string | null {
  if (isGroupNodeId(node.id)) return `${node.id} is a group, and groups do not nest.`
  if (node.external) return `${node.id} is provided by the game, and there is no file here to record a group on.`
  if (node.unresolved) return `${node.id} is not defined in this pack, so there is no file to record a group on.`
  if (!node.file) return `${node.id} has no file behind it.`
  return null
}

// ---------------------------------------------------------------------------
// Planning
// ---------------------------------------------------------------------------

export type GroupPlan =
  | {
      readonly ok: true
      readonly ops: readonly AnnotateOp[]
      /** One line for the status bar. */
      readonly summary: string
      readonly groupId: string
      /** Nodes this takes OUT of another group on the way in. */
      readonly moved: readonly string[]
      /** Nodes this takes out of `groupId` and does not put anywhere -- the ones a remove or an
       * ungroup ends the membership of. Told apart from `moved` because the panel has to know
       * which departures it ASKED for: a member that leaves a group without one of these behind
       * it left because its file was deleted or edited, and that is worth saying. */
      readonly leaving: readonly string[]
    }
  | { readonly ok: false; readonly reason: string }

function refuse(reason: string): GroupPlan {
  return { ok: false, reason }
}

function setOp(file: string, id: string, collapsed: boolean, name: string): AnnotateOp {
  return { file, path: '$', name: GROUP_DIRECTIVE, args: [id, collapsed ? 'collapsed' : 'expanded', ...nameWords(name)] }
}

/** How many `@featurelab:group` directives this node's file carries, ANYWHERE in it.
 *
 * NOT "on its root", which is what it counted before and what made "None" a half-measure. A
 * directive written a line below the opening brace attaches to the first key rather than to the
 * file, declares no group, and was therefore invisible to this count -- so a file holding a
 * working directive above the brace and a hand-written one below it was removed once, came back
 * still carrying the second, and rejoined the group the author had just left. */
function directiveCount(node: GroupNodeWire): number {
  return groupDirectivesOf(node).length
}

/** Taking a file OUT of every group it is in -- one op per directive it carries, not one op.
 *
 * ONE WAS A DATA BUG WEARING THE WORD "NONE". The engine's RemoveAnnotation takes the FIRST
 * directive of that name off and returns the file otherwise untouched, which is correct for a file
 * with one. A file with two -- which a hand edit or an interrupted batch can leave behind, and
 * which readGroups already reports -- came back still carrying the second, so choosing "None" on a
 * node showing "Patches" moved it silently into "Markers". The author asked to be in no group and
 * ended up in a different one, with nothing on screen saying so.
 *
 * Ops on one file apply in sequence to the same bytes (see the engine's methodAnnotateBatch), and
 * a remove that finds nothing returns the file unchanged, so asking N times is exactly "all of
 * them" and never more. At least one op always, so a node whose directives this view could not
 * parse is still cleaned up.
 *
 * AND EACH OP CARRIES THE PATH AND SPELLING OF THE DIRECTIVE IT IS FOR. The engine matches a
 * removal on name AND jsonPath exactly (jsonc.RemoveAnnotation), so N removals all addressed at
 * `$`/`group` take off N copies of the root one and leave a misplaced or oddly-capitalised
 * directive exactly where it was. That is the second half of the same bug: the panel said the
 * feature was in no group, the file still said it was, and the next reload put it back. A
 * removal aimed at a directive that is not there is not an error -- the engine returns the file
 * unchanged -- so this is never more than "all of them" either. */
function removeOps(node: GroupNodeWire & { file: string }): AnnotateOp[] {
  const found = groupDirectivesOf(node)
  if (found.length === 0) return [{ file: node.file, path: '$', name: GROUP_DIRECTIVE, remove: true }]
  return found.map((a) => ({ file: node.file, path: a.jsonPath, name: a.name, remove: true }))
}

/** The removals that have to go IN FRONT of a `setOp` on this file, or none.
 *
 * `setOp` writes `@featurelab:group` at `$`, and the engine replaces a directive matching that
 * name at that path -- exactly that one. Every OTHER group directive in the file survives it: a
 * hand-written one a line below the brace, and one spelled with a capital. So the ordinary act of
 * choosing a group from the inspector used to leave the file holding two, the second of them
 * permanently invisible, and "None" then took one off and the feature quietly rejoined the group.
 *
 * Empty for the file everybody actually has, which carries nought or one root directive; this
 * costs nothing until a file is already in the state it exists to end.
 *
 * ONE ROOT DIRECTIVE IS SPARED, NOT ALL OF THEM, and that is the variant this got wrong first
 * time. `setOp` overwrites exactly ONE `$`/`group` -- the engine's own writer replaces the first
 * match and returns -- so exactly one may be left standing for it to overwrite. A file holding
 * TWO lower-case `@featurelab:group` directives at `$` (which readGroups already warns about, so
 * it is a state this tool knows how to reach) matched the old filter twice, contributed no
 * removal at all, and came out of "choose a group" still holding a second root directive that
 * nothing on screen mentions -- the same defect as the misplaced and the capitalised one, one
 * variant over. Whichever copy the set op will land on is the one spared; every other directive
 * in the file, at any path and in any spelling, is removed first. */
function supersededRemoveOps(node: GroupNodeWire & { file: string }): AnnotateOp[] {
  let spared = false
  const ops: AnnotateOp[] = []
  for (const a of groupDirectivesOf(node)) {
    if (!spared && a.jsonPath === '$' && a.name === GROUP_DIRECTIVE) {
      spared = true
      continue
    }
    ops.push({ file: node.file, path: a.jsonPath, name: a.name, remove: true })
  }
  return ops
}

/** A set of a file's directive, with whatever the set would not have overwritten taken off first.
 * Ops on one file apply in sequence, so the order here is the order on disk. */
function setOpsFor(node: GroupNodeWire & { file: string }, id: string, collapsed: boolean, name: string): AnnotateOp[] {
  return [...supersededRemoveOps(node), setOp(node.file, id, collapsed, name)]
}

/** The nodes named, with their files, or the first reason one of them cannot be a member. */
function membersFor(graph: GroupGraph, nodeIds: readonly string[]): { ok: true; nodes: (GroupNodeWire & { file: string })[] } | { ok: false; reason: string } {
  const byId = new Map(graph.nodes.map((n) => [n.id, n]))
  const out: (GroupNodeWire & { file: string })[] = []
  const seen = new Set<string>()
  for (const id of nodeIds) {
    if (seen.has(id)) continue
    seen.add(id)
    const node = byId.get(id)
    if (node === undefined) return { ok: false, reason: `${id} is not in the graph.` }
    const why = groupableReason(node)
    if (why !== null) return { ok: false, reason: why }
    out.push(node as GroupNodeWire & { file: string })
  }
  return { ok: true, nodes: out }
}

function plural(n: number, word: string): string {
  return `${String(n)} ${word}${n === 1 ? '' : 's'}`
}

/** A new group of `nodeIds`, expanded, called `name`. Nodes already in another group are moved:
 * their directive is REWRITTEN rather than removed and re-added, since one file carries one. */
export function planCreate(graph: GroupGraph, view: GroupsView, nodeIds: readonly string[], name: string): GroupPlan {
  const problem = validateGroupName(name)
  if (problem !== null) return refuse(problem)
  if (nodeIds.length === 0) return refuse('Select at least one feature to group.')
  const members = membersFor(graph, nodeIds)
  if (!members.ok) return refuse(members.reason)
  const clean = normaliseGroupName(name)
  const id = slugForGroup(clean, view.byId.keys())
  const moved = members.nodes.filter((n) => view.memberOf.has(n.id)).map((n) => n.id)
  return {
    ok: true,
    ops: members.nodes.flatMap((n) => setOpsFor(n, id, false, clean)),
    summary: `Grouping ${plural(members.nodes.length, 'feature')} as "${clean}".`,
    groupId: id,
    moved,
    leaving: [],
  }
}

/** Every member rewritten with the new name; the id and the state stay. */
export function planRename(graph: GroupGraph, view: GroupsView, groupId: string, name: string): GroupPlan {
  const group = view.byId.get(groupId)
  if (group === undefined) return refuse(`There is no group ${groupId}.`)
  const problem = validateGroupName(name)
  if (problem !== null) return refuse(problem)
  const clean = normaliseGroupName(name)
  const members = membersFor(graph, group.memberIds)
  if (!members.ok) return refuse(members.reason)
  return {
    ok: true,
    ops: members.nodes.flatMap((n) => setOpsFor(n, group.id, group.collapsed, clean)),
    summary: `Renaming "${group.name}" to "${clean}".`,
    groupId: group.id,
    moved: [],
    leaving: [],
  }
}

/** Every member rewritten with the new state. Also the repair for members that disagree. */
export function planSetCollapsed(graph: GroupGraph, view: GroupsView, groupId: string, collapsed: boolean): GroupPlan {
  const group = view.byId.get(groupId)
  if (group === undefined) return refuse(`There is no group ${groupId}.`)
  const members = membersFor(graph, group.memberIds)
  if (!members.ok) return refuse(members.reason)
  return {
    ok: true,
    ops: members.nodes.flatMap((n) => setOpsFor(n, group.id, collapsed, group.name)),
    summary: `${collapsed ? 'Collapsing' : 'Expanding'} "${group.name}".`,
    groupId: group.id,
    moved: [],
    leaving: [],
  }
}

/** Adds `nodeIds` to an existing group. A node already in it is left alone; one in another group
 * is moved, which is one rewrite of its directive. */
export function planAdd(graph: GroupGraph, view: GroupsView, groupId: string, nodeIds: readonly string[]): GroupPlan {
  const group = view.byId.get(groupId)
  if (group === undefined) return refuse(`There is no group ${groupId}.`)
  const incoming = nodeIds.filter((id) => view.memberOf.get(id) !== group.id)
  if (incoming.length === 0) return refuse(`Already in "${group.name}".`)
  const members = membersFor(graph, incoming)
  if (!members.ok) return refuse(members.reason)
  const moved = members.nodes.filter((n) => view.memberOf.has(n.id)).map((n) => n.id)
  return {
    ok: true,
    ops: members.nodes.flatMap((n) => setOpsFor(n, group.id, group.collapsed, group.name)),
    summary: `Adding ${plural(members.nodes.length, 'feature')} to "${group.name}".`,
    groupId: group.id,
    moved,
    leaving: [],
  }
}

/** Takes `nodeIds` out of a group. Removing the last member removes the group, because the group
 * IS its members' directives and nothing else. */
export function planRemove(graph: GroupGraph, view: GroupsView, groupId: string, nodeIds: readonly string[]): GroupPlan {
  const group = view.byId.get(groupId)
  if (group === undefined) return refuse(`There is no group ${groupId}.`)
  const leaving = nodeIds.filter((id) => view.memberOf.get(id) === group.id)
  if (leaving.length === 0) return refuse(`None of those are in "${group.name}".`)
  const members = membersFor(graph, leaving)
  if (!members.ok) return refuse(members.reason)
  const last = leaving.length >= group.memberIds.length
  return {
    ok: true,
    ops: members.nodes.flatMap((n) => removeOps(n)),
    summary: last
      ? `Removing the last of "${group.name}", which ends the group.`
      : `Removing ${plural(members.nodes.length, 'feature')} from "${group.name}".`,
    groupId: group.id,
    moved: [],
    leaving: members.nodes.map((n) => n.id),
  }
}

/** Dissolves a group: every member's directive removed, every feature left exactly where it is. */
export function planUngroup(graph: GroupGraph, view: GroupsView, groupId: string): GroupPlan {
  const group = view.byId.get(groupId)
  if (group === undefined) return refuse(`There is no group ${groupId}.`)
  const members = membersFor(graph, group.memberIds)
  if (!members.ok) return refuse(members.reason)
  return {
    ok: true,
    ops: members.nodes.flatMap((n) => removeOps(n)),
    summary: `Ungrouping "${group.name}" -- ${plural(members.nodes.length, 'feature')} stay where they are.`,
    groupId: group.id,
    moved: [],
    leaving: members.nodes.map((n) => n.id),
  }
}

// ---------------------------------------------------------------------------
// The view graph
// ---------------------------------------------------------------------------

/** Folds each collapsed group into ONE synthetic node, edges re-pointed.
 *
 * The same shape webview/graph.ts's collapseCompounds has, for the same reasons: an edge that
 * leaves or enters a hidden member is KEPT and re-pointed at the card that now stands for it,
 * because those edges are the shape of the pack and the reason to collapse anything is to see
 * that shape; several members reaching the same outside node become one edge, since drawn four
 * times it is four arrowheads on one line; and an edge between two members of one group is
 * dropped, because a self-loop on a card would draw the inside as a decoration on the outside.
 *
 * The synthetic node is inserted where the group's first member was, so draw order -- and with it
 * which card lands on top when two overlap -- stays where the author would expect. It carries
 * `group` so the renderer can draw it from the node alone. Roots are kept for every node still
 * drawn, and a group card is a root when one of its members was and nothing outside now reaches
 * it -- the second half matters, because "starts here" on a card something points at is wrong.
 *
 * Expanded groups change nothing here: their members are drawn as themselves, inside a frame the
 * renderer draws from `expandedFrames`. */
export function collapseGroups<
  N extends { readonly id: string },
  E extends GroupEdgeWire,
  G extends { readonly nodes: readonly N[]; readonly edges: readonly E[]; readonly roots: readonly string[] },
>(graph: G, view: GroupsView): G {
  const collapsed = view.groups.filter((g) => g.collapsed)
  if (collapsed.length === 0) return graph
  const present = new Set(graph.nodes.map((n) => n.id))
  const ownerOf = new Map<string, string>()
  const firstMember = new Map<string, string>()
  for (const group of collapsed) {
    for (const member of group.memberIds) {
      if (!present.has(member)) continue
      ownerOf.set(member, groupNodeId(group.id))
      if (!firstMember.has(group.id)) firstMember.set(group.id, member)
    }
  }
  if (ownerOf.size === 0) return graph

  const nodes: N[] = []
  for (const node of graph.nodes) {
    const owner = ownerOf.get(node.id)
    if (owner === undefined) {
      nodes.push(node)
      continue
    }
    const group = collapsed.find((g) => groupNodeId(g.id) === owner)
    if (group !== undefined && firstMember.get(group.id) === node.id) {
      const memberIds = group.memberIds.filter((id) => present.has(id))
      const summary: GroupNodeSummary = { id: group.id, name: group.name, count: memberIds.length, memberIds }
      nodes.push({ id: owner, group: summary } as unknown as N)
    }
  }

  const edges: E[] = []
  const seen = new Set<string>()
  const entered = new Set<string>()
  for (const edge of graph.edges) {
    const from = ownerOf.get(edge.from) ?? edge.from
    const to = ownerOf.get(edge.to) ?? edge.to
    const touched = from !== edge.from || to !== edge.to
    if (touched && from === to) continue
    if (touched) {
      const key = `${from} ${to} ${edge.kind}`
      if (seen.has(key)) continue
      seen.add(key)
    }
    if (ownerOf.has(edge.to)) entered.add(to)
    edges.push(touched ? { ...edge, from, to } : edge)
  }

  const roots: string[] = []
  const rootSet = new Set(graph.roots)
  const groupRooted = new Set<string>()
  for (const id of graph.roots) {
    const owner = ownerOf.get(id)
    if (owner === undefined) roots.push(id)
    else if (!entered.has(owner)) groupRooted.add(owner)
  }
  for (const node of nodes) {
    if (groupRooted.has(node.id) && !rootSet.has(node.id)) roots.push(node.id)
  }

  return { ...graph, nodes, edges, roots }
}

/** Where each collapsed group's card goes: the top-left of its members' positions, so the card
 * sits where the group was rather than wherever an automatic layout would put a node nobody
 * placed. Members with no position contribute nothing; a group none of whose members has one gets
 * no entry, and the renderer's own fallback places it. */
export function groupCardPositions(
  view: GroupsView,
  positions: ReadonlyMap<string, { readonly x: number; readonly y: number }>,
): Map<string, { x: number; y: number }> {
  const out = new Map<string, { x: number; y: number }>()
  for (const group of view.groups) {
    if (!group.collapsed) continue
    let x = Infinity
    let y = Infinity
    for (const id of group.memberIds) {
      const at = positions.get(id)
      if (!at) continue
      x = Math.min(x, at.x)
      y = Math.min(y, at.y)
    }
    if (Number.isFinite(x) && Number.isFinite(y)) out.set(groupNodeId(group.id), { x, y })
  }
  return out
}

/** The frames the renderer draws for EXPANDED groups: which members, under what name. Only the
 * members actually in `graph`, so a frame is never drawn around a node that is not there. */
export function expandedFrames(
  view: GroupsView,
  graph: { readonly nodes: readonly { readonly id: string }[] },
): { groupId: string; name: string; memberIds: string[]; lone: boolean }[] {
  const present = new Set(graph.nodes.map((n) => n.id))
  const out: { groupId: string; name: string; memberIds: string[]; lone: boolean }[] = []
  for (const group of view.groups) {
    if (group.collapsed) continue
    const memberIds = group.memberIds.filter((id) => present.has(id))
    if (memberIds.length === 0) continue
    // A BRACKET ROUND ONE THING IS NOT A BRACKET. A group is several features somebody decided to
    // read as one, and a group of one is the remains of that decision: the other members were
    // deleted, or their directives were taken off, and what is left draws as an ordinary group
    // with a frame round it and a count of 1 in the sidebar -- indistinguishable from a group
    // somebody meant. Reported as a fact rather than as a fault, because a group of one is also
    // what you have for the moment between creating one and adding the second member to it. The
    // whole of the difference is that it is SAID.
    out.push({ groupId: group.id, name: group.name, memberIds, lone: group.memberIds.length === 1 })
  }
  return out
}
