// groups.ts -- author-declared groups of features, read from and written to the pack files.
//
// A group is PRESENTATION THE AUTHOR DECLARED: several features and rules the author decided to
// look at as one thing, with a name, and either spread out inside a frame or folded into one
// card. That is the whole of it. A group has no meaning to the game and no meaning to the engine;
// it is what a person thinks a pack is made of, written down so the next person opening the pack
// sees the same shape.
//
// Three decisions follow from that, and each rules something out:
//
//   - MEMBERSHIP, NAME AND STATE LIVE IN THE PACK FILES, as a `@featurelab:group` directive in a
//     comment on each member's root. Not in the per-user layout sidecar: a group is a statement
//     about the pack, and a statement kept where only one person can see it is a note to self,
//     not a shape. So collapsing a group -- which is also a statement, "these read as one" --
//     rewrites its members' files, and is committed with the pack like everything else in it.
//   - A GROUP IS NEVER INFERRED. Nothing here looks at names, directories or delegations and
//     decides that some features belong together. The only groups are the ones written down.
//   - EDITING A MEMBER CHANGES NOTHING ABOUT THE GROUP. This is the difference from a compound
//     (compounds/collapse.ts), whose files are GENERATED from its parameters and which therefore
//     ejects to plain nodes the moment one of them is edited by hand. A group's members were never
//     generated by anything; the directive is a label, and a label survives any edit to the thing
//     it is on.
//
// # The directive
//
//   // @featurelab:group <id> <expanded|collapsed> <name words...>
//
// on the ROOT of each member's file (JSONPath `$`). The id is a slug ([a-z0-9_-]+) derived from
// the name when the group is made and kept stable across renames, so a rename rewrites the name
// words and nothing else -- and so two groups can share a display name without becoming one. The
// state and the name are repeated in every member because there is no other file to put them in:
// a pack has no manifest of groups, and inventing one would be a file the engine has to skip and
// an author has to keep in step with N others.
//
// Repetition means members CAN disagree, and `readGroups` says what happens then: the commonest
// value wins, the disagreement is reported on the group, and nothing is silently rewritten. Two
// files that disagree about a name is a state somebody produced by editing a comment in a text
// editor, which is legitimate, and the editor's job is to show it and offer the fix, not to pick
// a side and overwrite the other.
//
// # Flat
//
// A feature belongs to at most one group and a group holds no groups. One directive per file is
// what makes the first true (a file with two is reported and the first is used); the second is
// simply not expressible in the directive, and that is deliberate -- nested groups are a tree
// editor's worth of interaction over a canvas whose whole difficulty is already density.
//
// # What this module does not do
//
// It never touches a file and never draws. `plan*` return the batch of directive writes and
// removals that an operation means, in the shape the engine's `annotateBatch` takes, and the
// webview posts them; `collapseGroups` returns a view graph and the renderer draws it. Both
// halves are pure so both are testable without a browser or an engine.

/** The directive's name, without the `@featurelab:` prefix. */
export const GROUP_DIRECTIVE = 'group'

/** The id prefix of the synthetic node a collapsed group draws as. Chosen so it cannot collide
 * with a feature identifier, which always carries a namespace and a colon after it -- `group:` IS
 * a namespace-shaped prefix, and a pack could in principle own it, so the check is stricter than
 * the prefix: see isGroupNodeId. */
export const GROUP_NODE_PREFIX = 'group:'

/** What a group id may look like. Lower-case, so a slug derived from any name is one. */
const GROUP_ID_PATTERN = /^[a-z0-9_-]+$/

// ---------------------------------------------------------------------------
// The wire, as this module needs it
// ---------------------------------------------------------------------------

/** One step of the engine's `annotateBatch`: the same three coordinates `annotate` takes, plus
 * `remove`, which takes the directive OUT instead of writing it. Spelled here, in the one module
 * that plans them, so the host relays them without re-shaping. */
export interface AnnotateOp {
  /** Pack-relative, as wire.GraphNode.File reports it. */
  readonly file: string
  /** What the directive is about, in jsonc.FormatPath's dialect; `$` for the file itself. */
  readonly path: string
  readonly name: string
  readonly args?: readonly string[]
  readonly remove?: boolean
}

/** The slice of wire.Annotation this module reads. */
export interface GroupAnnotationWire {
  readonly name: string
  readonly args?: readonly string[]
  readonly jsonPath: string
}

/** The slice of wire.GraphNode this module reads. */
export interface GroupNodeWire {
  readonly id: string
  readonly file?: string
  readonly unresolved?: boolean
  readonly external?: boolean
  readonly annotations?: readonly GroupAnnotationWire[]
}

export interface GroupEdgeWire {
  readonly from: string
  readonly to: string
  readonly kind: string
}

export interface GroupGraph {
  readonly nodes: readonly GroupNodeWire[]
  readonly edges: readonly GroupEdgeWire[]
  readonly roots: readonly string[]
}

/** What the renderer is handed on a collapsed group's synthetic node, so it can draw the card
 * from the node alone. Mirrored by render.ts's GraphNodeGroupWire. */
export interface GroupNodeSummary {
  readonly id: string
  readonly name: string
  readonly count: number
}

// ---------------------------------------------------------------------------
// Reading
// ---------------------------------------------------------------------------

export interface FeatureGroup {
  readonly id: string
  readonly name: string
  readonly collapsed: boolean
  /** In graph order. Never empty: a group with no members is not a group, it is the absence of
   * one, and `readGroups` never returns it. */
  readonly memberIds: readonly string[]
  /** Disagreements between members, one line each, for the panel to show as notes. */
  readonly warnings: readonly string[]
}

export interface GroupsView {
  /** In order of first appearance in the graph. */
  readonly groups: readonly FeatureGroup[]
  readonly byId: ReadonlyMap<string, FeatureGroup>
  /** Node id -> the id of the group it belongs to. */
  readonly memberOf: ReadonlyMap<string, string>
  /** Directives that could not be read as a group at all, one line each. */
  readonly warnings: readonly string[]
}

const EMPTY_VIEW: GroupsView = { groups: [], byId: new Map(), memberOf: new Map(), warnings: [] }

interface ParsedDirective {
  readonly id: string
  readonly collapsed: boolean
  readonly name: string
}

/** Reads one directive's arguments, or says why they are not a group. */
function parseDirective(args: readonly string[] | undefined): { ok: true; value: ParsedDirective } | { ok: false; why: string } {
  const list = args ?? []
  const id = list[0]
  const state = list[1]
  if (id === undefined || state === undefined || list.length < 3) {
    return { ok: false, why: 'it needs an id, a state and a name' }
  }
  if (!GROUP_ID_PATTERN.test(id)) return { ok: false, why: `"${id}" is not a group id (letters, digits, - and _ only)` }
  if (state !== 'expanded' && state !== 'collapsed') return { ok: false, why: `"${state}" is neither expanded nor collapsed` }
  const name = normaliseGroupName(list.slice(2).join(' '))
  if (name === '') return { ok: false, why: 'the name is empty' }
  return { ok: true, value: { id, collapsed: state === 'collapsed', name } }
}

/** The commonest value in a list, ties to the first seen, and whether there was any disagreement. */
function majority<T>(values: readonly T[], describe: (v: T) => string): { value: T; note: string | null } {
  const counts = new Map<T, number>()
  for (const v of values) counts.set(v, (counts.get(v) ?? 0) + 1)
  let best: T = values[0] as T
  let bestCount = 0
  for (const [v, n] of counts) {
    if (n > bestCount) {
      best = v
      bestCount = n
    }
  }
  if (counts.size <= 1) return { value: best, note: null }
  const parts = [...counts.entries()].map(([v, n]) => `${describe(v)} ×${String(n)}`)
  return { value: best, note: parts.join(', ') }
}

/** Every group the graph's files declare.
 *
 * Read from the nodes as handed in, so a caller that has already hidden a compound's children
 * gets groups without those children -- a node that is not drawn cannot be a member of anything
 * drawn. Nodes with no file carry no annotations and so are never members. */
export function readGroups(graph: GroupGraph): GroupsView {
  const members = new Map<string, { node: GroupNodeWire; directive: ParsedDirective }[]>()
  const order: string[] = []
  const warnings: string[] = []
  const perGroupWarnings = new Map<string, string[]>()

  for (const node of graph.nodes) {
    if (!node.file) continue
    const directives = (node.annotations ?? []).filter((a) => a.name === GROUP_DIRECTIVE && a.jsonPath === '$')
    const first = directives[0]
    if (first === undefined) continue
    const parsed = parseDirective(first.args)
    if (!parsed.ok) {
      warnings.push(`${node.id}: its @featurelab:group directive was ignored -- ${parsed.why}.`)
      continue
    }
    const id = parsed.value.id
    if (!members.has(id)) {
      members.set(id, [])
      order.push(id)
    }
    members.get(id)!.push({ node, directive: parsed.value })
    if (directives.length > 1) {
      const list = perGroupWarnings.get(id) ?? []
      list.push(`${node.id} carries ${String(directives.length)} group directives; the first one is used.`)
      perGroupWarnings.set(id, list)
    }
  }
  if (order.length === 0 && warnings.length === 0) return EMPTY_VIEW

  const groups: FeatureGroup[] = []
  const byId = new Map<string, FeatureGroup>()
  const memberOf = new Map<string, string>()
  for (const id of order) {
    const list = members.get(id)!
    const name = majority(list.map((m) => m.directive.name), (v) => `"${v}"`)
    const state = majority(list.map((m) => m.directive.collapsed), (v) => (v ? 'collapsed' : 'expanded'))
    const notes = [...(perGroupWarnings.get(id) ?? [])]
    if (name.note !== null) notes.push(`Members disagree about the name (${name.note}); showing the commoner one. Renaming fixes all of them.`)
    if (state.note !== null) notes.push(`Members disagree about being collapsed (${state.note}); showing the commoner state. Collapsing or expanding fixes all of them.`)
    const group: FeatureGroup = {
      id,
      name: name.value,
      collapsed: state.value,
      memberIds: list.map((m) => m.node.id),
      warnings: notes,
    }
    groups.push(group)
    byId.set(id, group)
    for (const m of list) memberOf.set(m.node.id, id)
  }
  return { groups, byId, memberOf, warnings }
}

/** The group a node belongs to, or null. */
export function groupOf(view: GroupsView, nodeId: string): FeatureGroup | null {
  const id = view.memberOf.get(nodeId)
  return id === undefined ? null : (view.byId.get(id) ?? null)
}

// ---------------------------------------------------------------------------
// Names and ids
// ---------------------------------------------------------------------------

/** A name as it is stored: trimmed, inner whitespace collapsed to single spaces. The directive's
 * arguments are whitespace-split on the way back in, so this is the only spelling that survives
 * a round trip, and normalising up front is what makes "what I typed" equal "what I get back". */
export function normaliseGroupName(raw: string): string {
  return raw.replace(/\s+/g, ' ').trim()
}

/** Why a name cannot be written, or null when it can. */
export function validateGroupName(name: string): string | null {
  const clean = normaliseGroupName(name)
  if (clean === '') return 'A group needs a name.'
  // A directive may sit in a block comment, where this sequence would end the comment early and
  // turn the rest of the name into JSON the engine refuses.
  if (clean.includes('*/')) return 'A group name cannot contain "*/".'
  return null
}

/** The words a name is written as, one argument each. */
function nameWords(name: string): string[] {
  return normaliseGroupName(name).split(' ')
}

/** A fresh id for a group called `name`: the name as a slug, suffixed when the slug is taken.
 *
 * Stable across renames by construction -- it is only ever computed here, at creation -- so the
 * id is a handle and not a second copy of the name. */
export function slugForGroup(name: string, taken: Iterable<string>): string {
  const used = new Set(taken)
  const base =
    normaliseGroupName(name)
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-+|-+$/g, '') || 'group'
  if (!used.has(base)) return base
  for (let n = 2; n < 10_000; n++) {
    const candidate = `${base}-${String(n)}`
    if (!used.has(candidate)) return candidate
  }
  return `${base}-${String(Date.now())}`
}

export function groupNodeId(groupId: string): string {
  return `${GROUP_NODE_PREFIX}${groupId}`
}

/** The group id a synthetic node stands for, or null for an ordinary node. Stricter than the
 * prefix alone: the rest must be a valid group id, which no feature identifier's path is likely
 * to be, and which is what a caller then looks up anyway. */
export function groupIdOfNode(nodeId: string): string | null {
  if (!nodeId.startsWith(GROUP_NODE_PREFIX)) return null
  const rest = nodeId.slice(GROUP_NODE_PREFIX.length)
  return GROUP_ID_PATTERN.test(rest) ? rest : null
}

export function isGroupNodeId(nodeId: string): boolean {
  return groupIdOfNode(nodeId) !== null
}

// ---------------------------------------------------------------------------
// What may be grouped
// ---------------------------------------------------------------------------

/** Why a node cannot be a member, or null when it can.
 *
 * Only a node with a real file can carry the directive, so only a node with a real file can be a
 * member: not a dangling reference, not one of the game's own features, not the synthetic card
 * of another group. A hidden child of a collapsed compound is not in the graph this module is
 * handed, so it never reaches here -- and that is right: the compound stands for it. */
export function groupableReason(node: GroupNodeWire): string | null {
  if (isGroupNodeId(node.id)) return `${node.id} is a group, and groups do not nest.`
  if (node.external) return `${node.id} is provided by the game, and there is no file here to record a group on.`
  if (node.unresolved) return `${node.id} is not defined in this pack, so there is no file to record a group on.`
  if (!node.file) return `${node.id} has no file behind it.`
  return null
}

// ---------------------------------------------------------------------------
// Planning
// ---------------------------------------------------------------------------

export type GroupPlan =
  | {
      readonly ok: true
      readonly ops: readonly AnnotateOp[]
      /** One line for the status bar. */
      readonly summary: string
      readonly groupId: string
      /** Nodes this takes OUT of another group on the way in. */
      readonly moved: readonly string[]
    }
  | { readonly ok: false; readonly reason: string }

function refuse(reason: string): GroupPlan {
  return { ok: false, reason }
}

function setOp(file: string, id: string, collapsed: boolean, name: string): AnnotateOp {
  return { file, path: '$', name: GROUP_DIRECTIVE, args: [id, collapsed ? 'collapsed' : 'expanded', ...nameWords(name)] }
}

function removeOp(file: string): AnnotateOp {
  return { file, path: '$', name: GROUP_DIRECTIVE, remove: true }
}

/** The nodes named, with their files, or the first reason one of them cannot be a member. */
function membersFor(graph: GroupGraph, nodeIds: readonly string[]): { ok: true; nodes: (GroupNodeWire & { file: string })[] } | { ok: false; reason: string } {
  const byId = new Map(graph.nodes.map((n) => [n.id, n]))
  const out: (GroupNodeWire & { file: string })[] = []
  const seen = new Set<string>()
  for (const id of nodeIds) {
    if (seen.has(id)) continue
    seen.add(id)
    const node = byId.get(id)
    if (node === undefined) return { ok: false, reason: `${id} is not in the graph.` }
    const why = groupableReason(node)
    if (why !== null) return { ok: false, reason: why }
    out.push(node as GroupNodeWire & { file: string })
  }
  return { ok: true, nodes: out }
}

function plural(n: number, word: string): string {
  return `${String(n)} ${word}${n === 1 ? '' : 's'}`
}

/** A new group of `nodeIds`, expanded, called `name`. Nodes already in another group are moved:
 * their directive is REWRITTEN rather than removed and re-added, since one file carries one. */
export function planCreate(graph: GroupGraph, view: GroupsView, nodeIds: readonly string[], name: string): GroupPlan {
  const problem = validateGroupName(name)
  if (problem !== null) return refuse(problem)
  if (nodeIds.length === 0) return refuse('Select at least one feature to group.')
  const members = membersFor(graph, nodeIds)
  if (!members.ok) return refuse(members.reason)
  const clean = normaliseGroupName(name)
  const id = slugForGroup(clean, view.byId.keys())
  const moved = members.nodes.filter((n) => view.memberOf.has(n.id)).map((n) => n.id)
  return {
    ok: true,
    ops: members.nodes.map((n) => setOp(n.file, id, false, clean)),
    summary: `Grouping ${plural(members.nodes.length, 'feature')} as "${clean}".`,
    groupId: id,
    moved,
  }
}

/** Every member rewritten with the new name; the id and the state stay. */
export function planRename(graph: GroupGraph, view: GroupsView, groupId: string, name: string): GroupPlan {
  const group = view.byId.get(groupId)
  if (group === undefined) return refuse(`There is no group ${groupId}.`)
  const problem = validateGroupName(name)
  if (problem !== null) return refuse(problem)
  const clean = normaliseGroupName(name)
  const members = membersFor(graph, group.memberIds)
  if (!members.ok) return refuse(members.reason)
  return {
    ok: true,
    ops: members.nodes.map((n) => setOp(n.file, group.id, group.collapsed, clean)),
    summary: `Renaming "${group.name}" to "${clean}".`,
    groupId: group.id,
    moved: [],
  }
}

/** Every member rewritten with the new state. Also the repair for members that disagree. */
export function planSetCollapsed(graph: GroupGraph, view: GroupsView, groupId: string, collapsed: boolean): GroupPlan {
  const group = view.byId.get(groupId)
  if (group === undefined) return refuse(`There is no group ${groupId}.`)
  const members = membersFor(graph, group.memberIds)
  if (!members.ok) return refuse(members.reason)
  return {
    ok: true,
    ops: members.nodes.map((n) => setOp(n.file, group.id, collapsed, group.name)),
    summary: `${collapsed ? 'Collapsing' : 'Expanding'} "${group.name}".`,
    groupId: group.id,
    moved: [],
  }
}

/** Adds `nodeIds` to an existing group. A node already in it is left alone; one in another group
 * is moved, which is one rewrite of its directive. */
export function planAdd(graph: GroupGraph, view: GroupsView, groupId: string, nodeIds: readonly string[]): GroupPlan {
  const group = view.byId.get(groupId)
  if (group === undefined) return refuse(`There is no group ${groupId}.`)
  const incoming = nodeIds.filter((id) => view.memberOf.get(id) !== group.id)
  if (incoming.length === 0) return refuse(`Already in "${group.name}".`)
  const members = membersFor(graph, incoming)
  if (!members.ok) return refuse(members.reason)
  const moved = members.nodes.filter((n) => view.memberOf.has(n.id)).map((n) => n.id)
  return {
    ok: true,
    ops: members.nodes.map((n) => setOp(n.file, group.id, group.collapsed, group.name)),
    summary: `Adding ${plural(members.nodes.length, 'feature')} to "${group.name}".`,
    groupId: group.id,
    moved,
  }
}

/** Takes `nodeIds` out of a group. Removing the last member removes the group, because the group
 * IS its members' directives and nothing else. */
export function planRemove(graph: GroupGraph, view: GroupsView, groupId: string, nodeIds: readonly string[]): GroupPlan {
  const group = view.byId.get(groupId)
  if (group === undefined) return refuse(`There is no group ${groupId}.`)
  const leaving = nodeIds.filter((id) => view.memberOf.get(id) === group.id)
  if (leaving.length === 0) return refuse(`None of those are in "${group.name}".`)
  const members = membersFor(graph, leaving)
  if (!members.ok) return refuse(members.reason)
  const last = leaving.length >= group.memberIds.length
  return {
    ok: true,
    ops: members.nodes.map((n) => removeOp(n.file)),
    summary: last
      ? `Removing the last of "${group.name}", which ends the group.`
      : `Removing ${plural(members.nodes.length, 'feature')} from "${group.name}".`,
    groupId: group.id,
    moved: [],
  }
}

/** Dissolves a group: every member's directive removed, every feature left exactly where it is. */
export function planUngroup(graph: GroupGraph, view: GroupsView, groupId: string): GroupPlan {
  const group = view.byId.get(groupId)
  if (group === undefined) return refuse(`There is no group ${groupId}.`)
  const members = membersFor(graph, group.memberIds)
  if (!members.ok) return refuse(members.reason)
  return {
    ok: true,
    ops: members.nodes.map((n) => removeOp(n.file)),
    summary: `Ungrouping "${group.name}" -- ${plural(members.nodes.length, 'feature')} stay where they are.`,
    groupId: group.id,
    moved: [],
  }
}

// ---------------------------------------------------------------------------
// The view graph
// ---------------------------------------------------------------------------

/** Folds each collapsed group into ONE synthetic node, edges re-pointed.
 *
 * The same shape webview/graph.ts's collapseCompounds has, for the same reasons: an edge that
 * leaves or enters a hidden member is KEPT and re-pointed at the card that now stands for it,
 * because those edges are the shape of the pack and the reason to collapse anything is to see
 * that shape; several members reaching the same outside node become one edge, since drawn four
 * times it is four arrowheads on one line; and an edge between two members of one group is
 * dropped, because a self-loop on a card would draw the inside as a decoration on the outside.
 *
 * The synthetic node is inserted where the group's first member was, so draw order -- and with it
 * which card lands on top when two overlap -- stays where the author would expect. It carries
 * `group` so the renderer can draw it from the node alone. Roots are kept for every node still
 * drawn, and a group card is a root when one of its members was and nothing outside now reaches
 * it -- the second half matters, because "starts here" on a card something points at is wrong.
 *
 * Expanded groups change nothing here: their members are drawn as themselves, inside a frame the
 * renderer draws from `expandedFrames`. */
export function collapseGroups<
  N extends { readonly id: string },
  E extends GroupEdgeWire,
  G extends { readonly nodes: readonly N[]; readonly edges: readonly E[]; readonly roots: readonly string[] },
>(graph: G, view: GroupsView): G {
  const collapsed = view.groups.filter((g) => g.collapsed)
  if (collapsed.length === 0) return graph
  const present = new Set(graph.nodes.map((n) => n.id))
  const ownerOf = new Map<string, string>()
  const firstMember = new Map<string, string>()
  for (const group of collapsed) {
    for (const member of group.memberIds) {
      if (!present.has(member)) continue
      ownerOf.set(member, groupNodeId(group.id))
      if (!firstMember.has(group.id)) firstMember.set(group.id, member)
    }
  }
  if (ownerOf.size === 0) return graph

  const nodes: N[] = []
  for (const node of graph.nodes) {
    const owner = ownerOf.get(node.id)
    if (owner === undefined) {
      nodes.push(node)
      continue
    }
    const group = collapsed.find((g) => groupNodeId(g.id) === owner)
    if (group !== undefined && firstMember.get(group.id) === node.id) {
      const count = group.memberIds.filter((id) => present.has(id)).length
      const summary: GroupNodeSummary = { id: group.id, name: group.name, count }
      nodes.push({ id: owner, group: summary } as unknown as N)
    }
  }

  const edges: E[] = []
  const seen = new Set<string>()
  const entered = new Set<string>()
  for (const edge of graph.edges) {
    const from = ownerOf.get(edge.from) ?? edge.from
    const to = ownerOf.get(edge.to) ?? edge.to
    const touched = from !== edge.from || to !== edge.to
    if (touched && from === to) continue
    if (touched) {
      const key = `${from} ${to} ${edge.kind}`
      if (seen.has(key)) continue
      seen.add(key)
    }
    if (ownerOf.has(edge.to)) entered.add(to)
    edges.push(touched ? { ...edge, from, to } : edge)
  }

  const roots: string[] = []
  const rootSet = new Set(graph.roots)
  const groupRooted = new Set<string>()
  for (const id of graph.roots) {
    const owner = ownerOf.get(id)
    if (owner === undefined) roots.push(id)
    else if (!entered.has(owner)) groupRooted.add(owner)
  }
  for (const node of nodes) {
    if (groupRooted.has(node.id) && !rootSet.has(node.id)) roots.push(node.id)
  }

  return { ...graph, nodes, edges, roots }
}

/** Where each collapsed group's card goes: the top-left of its members' positions, so the card
 * sits where the group was rather than wherever an automatic layout would put a node nobody
 * placed. Members with no position contribute nothing; a group none of whose members has one gets
 * no entry, and the renderer's own fallback places it. */
export function groupCardPositions(
  view: GroupsView,
  positions: ReadonlyMap<string, { readonly x: number; readonly y: number }>,
): Map<string, { x: number; y: number }> {
  const out = new Map<string, { x: number; y: number }>()
  for (const group of view.groups) {
    if (!group.collapsed) continue
    let x = Infinity
    let y = Infinity
    for (const id of group.memberIds) {
      const at = positions.get(id)
      if (!at) continue
      x = Math.min(x, at.x)
      y = Math.min(y, at.y)
    }
    if (Number.isFinite(x) && Number.isFinite(y)) out.set(groupNodeId(group.id), { x, y })
  }
  return out
}

/** The frames the renderer draws for EXPANDED groups: which members, under what name. Only the
 * members actually in `graph`, so a frame is never drawn around a node that is not there. */
export function expandedFrames(view: GroupsView, graph: { readonly nodes: readonly { readonly id: string }[] }): { groupId: string; name: string; memberIds: string[] }[] {
  const present = new Set(graph.nodes.map((n) => n.id))
  const out: { groupId: string; name: string; memberIds: string[] }[] = []
  for (const group of view.groups) {
    if (group.collapsed) continue
    const memberIds = group.memberIds.filter((id) => present.has(id))
    if (memberIds.length === 0) continue
    out.push({ groupId: group.id, name: group.name, memberIds })
  }
  return out
}
