// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AskForTextureDownload() {
  return window['go']['main']['App']['AskForTextureDownload']();
}

export function BlockTexturesEnabled() {
  return window['go']['main']['App']['BlockTexturesEnabled']();
}

export function DeclineTextures() {
  return window['go']['main']['App']['DeclineTextures']();
}

export function EnsureTextures(arg1) {
  return window['go']['main']['App']['EnsureTextures'](arg1);
}

export function Generate(arg1) {
  return window['go']['main']['App']['Generate'](arg1);
}

export function GenerateGrown(arg1) {
  return window['go']['main']['App']['GenerateGrown'](arg1);
}

export function ListEnvironments() {
  return window['go']['main']['App']['ListEnvironments']();
}

export function ListPackItems() {
  return window['go']['main']['App']['ListPackItems']();
}

export function LoadAtlas() {
  return window['go']['main']['App']['LoadAtlas']();
}

export function LoadPack(arg1) {
  return window['go']['main']['App']['LoadPack'](arg1);
}

export function SelectPackDirectory() {
  return window['go']['main']['App']['SelectPackDirectory']();
}

export function TextureStatus() {
  return window['go']['main']['App']['TextureStatus']();
}
