// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wire} from '../models';
import {main} from '../models';

export function AskForTextureDownload():Promise<boolean>;

export function BlockTexturesEnabled():Promise<boolean>;

export function DeclineTextures():Promise<void>;

export function EnsureTextures(arg1:boolean):Promise<string>;

export function Generate(arg1:wire.GenerateParams):Promise<string>;

export function GenerateGrown(arg1:wire.GenerateParams):Promise<string>;

export function ListEnvironments():Promise<Array<main.EnvironmentOption>>;

export function ListPackItems():Promise<Array<main.PackItem>>;

export function LoadAtlas():Promise<string>;

export function LoadPack(arg1:string):Promise<main.LoadPackResult>;

export function SelectPackDirectory():Promise<string>;

export function TextureStatus():Promise<string>;
